export const UNIVERSITIES_LIST_REQUEST = 'UNIVERSITIES_LIST_REQUEST'
export const UNIVERSITIES_ADD_REQUEST = 'UNIVERSITIES_ADD_REQUEST'
export const UNIVERSITIES_DELETE_REQUEST = 'UNIVERSITIES_DELETE_REQUEST'
